title: Uncertainty Estimation for Dense Prediction Tasks
description: Uncertainty Estimation for Dense Prediction Tasks Tutorial at ICCV'21
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
